-- Create todos table
create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  completed boolean not null default false,
  created_at timestamp with time zone not null default now()
);

-- Enable Row Level Security
alter table public.todos enable row level security;

-- Users can only read their own todos
create policy "Users can view their own todos"
  on public.todos for select
  using (auth.uid() = user_id);

-- Users can only insert their own todos
create policy "Users can insert their own todos"
  on public.todos for insert
  with check (auth.uid() = user_id);

-- Users can only update their own todos
create policy "Users can update their own todos"
  on public.todos for update
  using (auth.uid() = user_id);

-- Users can only delete their own todos
create policy "Users can delete their own todos"
  on public.todos for delete
  using (auth.uid() = user_id);

-- Create index for faster queries
create index if not exists todos_user_id_idx on public.todos (user_id);
create index if not exists todos_created_at_idx on public.todos (created_at desc);
